### ISSUE TITLE
Release publique du bot

### ISSUE THREAD

**Issue by kekaaafm** [Edu-Focus/EduBot#11]
Bonjour/Bonsoir.

Comme vous le savez (ou pas) le bot est uniquement disponible sur un serveur de test et n'a donc pas d’utilité pour Edu-Focus.
Mon idée serait de faire tourner une app discord avec le code de la master (stable).
Pour éviter de faire une Marc (méthode de leak de token dans le code github) le roken sera uniquement sur le RPI qui hébergera le programme et ne sera jamais utilisé dans la branche dev (je garderai le token du bot de test comme ça on est bon).
Grace a ça, le bot pourra rajouter de la vie dans le serveur discord et permettra d'automatiser certaines taches et me permettra d'élargir les possibilités qui me sont offertes en terme de commandes (car faire une commande de ban sur un serveur de test c'est pas très utile)

En espérant que vous comprendrez ma démarche,
Marc

**Comment by ghost** [comment]
Hein ?
Genre faire un bot public ? En soit c'est une bonne idée
mais que si des personnes connaissent le truc
Sinon, faut voir les endpoints de l'API pour pouvoir faire de la visualisation de cours !

**Comment by kekaaafm** [comment]
Publique pas dans le sens "tout le monde peut avoir le bot sur son serv" mais publique dans le sens "le bot sera sur le serveur d'Edu-Focus"

**Comment by kekaaafm** [comment]
Je l'ai fait.
Si certains se sentent de l'installer, libre a vous de le faire (une instance "indev" reste accessible sur le serveur de test https://edu-foc.us/discord-sandbox)
Voila voila, je ferme cette issue
