### ISSUE TITLE
Vers une beta publique ?

### ISSUE THREAD

**Issue by kekaaafm** [Edu-Focus/EduBot#14]
Comme on peut le constater assez facilement, **EduBot** est assez tourné sur **son propre écosystème** rendant inutile l'utilisation par tous .
Sérieusement, tout le monde ne sait pas setup le code ni remplir les fichiers de config comme il le faut sans s'être déjà intéressé au développement du bot.

C'est pour ça que je propose une **vraie** version (BETA) **publique** du bot qui pourra être utilisée par tous (hrem hrem [Release publique du bot #11](https://github.com/Edu-Focus/EduBot/issues/11) ).
Ce bot sera une version "**modifié/bridé**" de la branche "**master**" car j'ai pas envie de laisser certaines commandes au public.

Bien sûr j'éditerais le **README.md** de la master pour que si jamais certains le souhaitent, puissent utiliser le code source comme ils le souhaitent (histoire de ne pas restreindre le public a une version bridé) mais qu'il devra héberger a ses propres frais, ce qui ne sera pas le cas de la version publique **si approuvée**.

**Comment by retouching** [comment]
>Sérieusement, tout le monde ne sait pas setup le code ni remplir les fichiers de config comme il le faut [...] C'est pour ça que je propose une vraie version (BETA) publique du bot qui pourra être utilisée par tous

Bah en sois c'est la meilleur solution pour que ça sois """""user friendly""""".

> j'ai pas envie de laisser certaines commandes au public.

Après pour ça, tu peux faire des commandes pour le staff uniquement

**Comment by kekaaafm** [comment]
>>Sérieusement, tout le monde ne sait pas setup le code ni remplir les fichiers de config comme il le faut [...] C'est pour ça que je propose une vraie version (BETA) publique du bot qui pourra être utilisée par tous
>
>Bah en sois c'est la meilleur solution pour que ça sois """""user friendly""""".

J'comprends pas...

>> j'ai pas envie de laisser certaines commandes au public.
>
>Après pour ça, tu peux faire des commandes pour le staff uniquement

C'est déjà le cas mais je vois pas l’intérêt de laisser un bot au public avec 80% (j'y vais fort), des fonctionnalités de restreintes

**Comment by retouching** [comment]
> > > Sérieusement, tout le monde ne sait pas setup le code ni remplir les fichiers de config comme il le faut [...] C'est pour ça que je propose une vraie version (BETA) publique du bot qui pourra être utilisée par tous
> > 
> > 
> > Bah en sois c'est la meilleur solution pour que ça sois """""user friendly""""".
> 
> J'comprends pas...

De base, faut setup le bot nous même si on veux l'utiliser non ? (j'ai rien vue dans le readme pour l'invité donc c'est ce que j'ai conclue) alors que dans ta request, ce que j'ai compris c'est que on pourra direct inviter un bot et l'utiliser

> > > j'ai pas envie de laisser certaines commandes au public.
> > 
> > 
> > Après pour ça, tu peux faire des commandes pour le staff uniquement
> 
> C'est déjà le cas mais je vois pas l’intérêt de laisser un bot au public avec 80% (j'y vais fort), des fonctionnalités de restreintes

Boarf tu peux toujours tester et voir si ça vaut le coup, de toute façon t'as rien à perdre à faire des tests en publique

**Comment by kekaaafm** [comment]
>>>>Sérieusement, tout le monde ne sait pas setup le code ni remplir les fichiers de config comme il le faut [...] C'est pour ça que je propose une vraie version (BETA) publique du bot qui pourra être utilisée par tous
>>>
>>>Bah en sois c'est la meilleur solution pour que ça sois """""user friendly""""".
>>
>>J'comprends pas...
>
>De base, faut setup le bot nous même si on veux l'utiliser non ? (j'ai rien vue dans le readme pour l'invité donc c'est ce que j'ai conclue) alors que dans ta request, ce que j'ai compris c'est que on pourra direct inviter un bot et l'utiliser

Il y existe [un lien pour l'inviter que j'ai pas encore mis dans le readme.md](https://edu-foc.us/bot) mais sinon faut le setup et sans check un peu partout on a tout rempli ou pas c'est un peu compliqué
Mais le pb c'est que certaines commandes ne marchent que sur le [serveur discord d'Edu-Focus](https://edu-foc.us/ds)

>>>>j'ai pas envie de laisser certaines commandes au public.
>>>
>>>Après pour ça, tu peux faire des commandes pour le staff uniquement
>>
>>C'est déjà le cas mais je vois pas l’intérêt de laisser un bot au public avec 80% (j'y vais fort), des fonctionnalités de restreintes
>
>Boarf tu peux toujours tester et voir si ça vaut le coup, de toute façon t'as rien à perdre à faire des tests en publique

Ok donc si je comprends bien tu es pour le lancement d'une beta publique ?

**Comment by GribouilleVert** [comment]
Alors juste comme ca, le bot ne peut pas être invité par les gens qui sont externes à la team. (ca vaut aussi pour le beta)
![image](https://user-images.githubusercontent.com/29147674/71704656-da31b580-2ddb-11ea-8577-594aaf6c97f3.png)

**Comment by kekaaafm** [comment]
Ah oui xD
