### ISSUE TITLE
Création d'une branche Stable et suppression de la Stable ?

### ISSUE THREAD

**Issue by kekaaafm** [Edu-Focus/EduBot#3]
Je voudrais savoir si c'était judicieux de créer une branche "Stable" et de supprimer la master (En passant la Stable en default)

**Comment by Rom1-J** [comment]
L’intérêt ?

**Comment by kekaaafm** [comment]
Après réflexion aucun, désolé :sweat_smile: 

_Sent from my Galaxy S7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
