### ISSUE TITLE
Rendre le code plus agréable à utiliser, faire et lire

### ISSUE THREAD

**Issue by GribouilleVert** [Edu-Focus/EduBot#6]
Il faut absolument refaire le code et le splitter en plusieurs fichiers, le rendre compatible avec l'utilisation d'une bdd, faire des classes. on a pas inventé require() pour faire joli.

**Comment by ghost** [comment]
pour rendre le code plus lisible, ne pas utiliser des embeds objets est une solution
éviter les switch aussi, et priviligier les single-lines condition
aussi éviter les répétitions

**Comment by GribouilleVert** [comment]
Pour plus de détails, fournir de l'aide, etc...
Répondez a l'issue ou sur [le salon discord d'edu-focus](https://discord.gg/u2TBtjE).

(le commentaire juste au dessus est un bon exemple)

**Comment by kekaaafm** [comment]
Je close ?
