### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by kekaaafm** [Edu-Focus/EduBot#9]
@Rom1-J Tu m'explique l'utilité du owner id + administrator si les ids sont vérifiés dynamiquement et demandés a chaque action d'administration à l'API d'Edu-Focus ?

**Comment by Rom1-J** [comment]
aucun si tel est le cas.
tu peux les degager

**Comment by kekaaafm** [comment]
Bon ben ça saute au prochain commit xD
Merci beaucoup de ton aide !
